# The keys from your SonarCloud dashboard
sonar.organization=chielfun2
sonar.projectKey=chielfun2_chielfun2.github.io

# Tells SonarQube where your source code is
sonar.sources=.

# Stops SonarQube from scanning your dependencies and build folders
sonar.exclusions=**/node_modules/**,**/out/**,**/dist/**,**/*.spec.js,**/*.test.js